// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cttbutdnwynqdoayhpaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0dGJ1dGRud3lucWRvYXlocGFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MTY2OTQsImV4cCI6MjA3MjM5MjY5NH0.-wykWq5VPjQtrR5fRdWCgD9tgv-S71b4wcauP6joHog";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
